# -*- coding: utf-8 -*-
"""AmitMatplotlib.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qo0GSUdXjgnsHGRRxEgHi_sHVc2qXxHr
"""

import matplotlib.pyplot as plt
import numpy as np

xpts = np.array([0,4])
ypts = np.array([0,100])

plt.plot(xpts, ypts)
plt.show()