# -*- coding: utf-8 -*-
"""AmitNumpy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O10tbdtY3w8XqV3FTrD2xYl-lwCUjwYT
"""

import numpy as np

arr = np.array((1, 2, 3))
print("Array = ",arr)

print(type(arr))