# -*- coding: utf-8 -*-
"""Amit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/AmtD/Content/blob/master/Amit.ipynb
"""

print("Studyopedia sample Python program....")

"""Sample program to sum two numbers in Python

"""

a = 10
b = 20
c = a + b
print("Sum = ",c)