# -*- coding: utf-8 -*-
"""AmitPandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IA0-5_6-WNEJ0hAqxIcw4Purz-kBZIzu
"""

import pandas as pd

mylist = [50, 100, 150, 200, 250, 300]

res = pd.Series(mylist)

print("Series = \n",res)